# Generated by Django 2.1.3 on 2018-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(default='상시', max_length=10),
            preserve_default=False,
        ),
    ]
