# Generated by Django 2.1.3 on 2018-12-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181201_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='site_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
