# Generated by Django 2.1.3 on 2018-11-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_point', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='gift_card',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='giftcardtype',
            name='use_point',
        ),
        migrations.DeleteModel(
            name='GiftCard',
        ),
        migrations.DeleteModel(
            name='GiftCardType',
        ),
    ]
