# Generated by Django 2.1.3 on 2018-11-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardtype',
            name='available_day_limit',
            field=models.DateField(),
        ),
    ]
