# Generated by Django 2.1.4 on 2018-12-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usepointcategory',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
