# Generated by Django 2.1.3 on 2018-11-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_point', '0002_auto_20181127_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usepoint',
            options={'ordering': ['pk']},
        ),
    ]
