# Generated by Django 2.1.3 on 2018-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181126_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_available_use_category_limit',
            field=models.ManyToManyField(blank=True, to='use_point.UsePointCategory'),
        ),
    ]
