# Generated by Django 2.1.4 on 2018-12-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181214_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_choices_name',
            field=models.CharField(choices=[('1', '루키몽'), ('2', '실버몽'), ('3', '골드몽'), ('4', '파워몽'), ('5', '슈퍼몽')], max_length=2, unique=True),
        ),
    ]
