# Generated by Django 2.1.3 on 2018-11-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181114_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_available_use_category_limit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='use_point.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='members.Rating'),
        ),
    ]
