# Generated by Django 2.1.3 on 2018-11-21 02:15

import django.contrib.auth.models
from django.db import migrations
import members.manager


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181114_2044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('adminManager', members.manager.UserAdminManager()),
                ('normalManager', members.manager.UserNormalManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
