# Generated by Django 2.1.4 on 2018-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181201_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default='1999-01-09'),
            preserve_default=False,
        ),
    ]
