# Generated by Django 2.1.3 on 2018-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20181121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='birthday_benefit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='cash_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='charge_support_benefit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='happy_day_benefit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_achieve_benefit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ticket_count',
            field=models.IntegerField(),
        ),
    ]
