# Generated by Django 2.1.3 on 2018-11-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Address',
        ),
    ]
