# Generated by Django 2.1.3 on 2018-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_point', '0002_auto_20181114_2034'),
        ('members', '0004_auto_20181114_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online_available_use_category_limit',
        ),
        migrations.AddField(
            model_name='user',
            name='online_available_use_category_limit',
            field=models.ManyToManyField(to='use_point.Category'),
        ),
    ]
