# Generated by Django 2.1.4 on 2018-12-18 10:41

from django.db import migrations, models
import django.db.models.deletion
import giftcard.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='images/shop_image')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_card_unique_id', models.CharField(default=giftcard.models.increment_giftcard_cnt, editable=False, max_length=9)),
                ('amount', models.IntegerField()),
                ('is_hotdeal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('h', 'hot'), ('m', 'mobile')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HappyGiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_card_unique_id', models.CharField(default=giftcard.models.increment_happycard_cnt, editable=False, max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('delivery_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'EMAIL'), ('address', 'address')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=15)),
                ('is_purchase', models.BooleanField(default=False)),
                ('full_amount', models.PositiveIntegerField()),
                ('delivery_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'EMAIL'), ('address', 'address')], max_length=10)),
                ('_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('_sms', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGiftCardAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.HappyGiftCard')),
                ('order_gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.OrderGiftCard')),
            ],
        ),
        migrations.CreateModel(
            name='PINGiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.CharField(max_length=30)),
                ('is_used', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.OrderGiftCardAmount')),
            ],
        ),
    ]
