# Generated by Django 2.1.3 on 2018-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('pin', models.CharField(max_length=18)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_day_limit', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('is_hotdeal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbering', models.CharField(max_length=20)),
                ('content', models.CharField(choices=[('d', '택배 선물'), ('e', '이메일'), ('s', 'SMS'), ('b', '영수증'), ('m1', '모바일 상품권'), ('m2', '사용처 전용 모바일 상품권')], max_length=2)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card_type', models.ManyToManyField(to='giftcard.GiftCardType')),
            ],
        ),
    ]
