# Generated by Django 2.1.3 on 2018-11-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='user_id',
        ),
    ]
