# Generated by Django 2.1.3 on 2018-11-25 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftcard', '0001_initial'),
        ('use_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcard',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordergiftcard',
            name='order_with',
            field=models.ManyToManyField(blank=True, related_name='_ordergiftcard_order_with_+', to='giftcard.OrderGiftCard'),
        ),
        migrations.AddField(
            model_name='giftcardtype',
            name='use_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='use_point.UsePoint'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.GiftCardType'),
        ),
    ]
