# Generated by Django 2.1.4 on 2018-12-14 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giftcard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcardtype',
            name='mall_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.GiftCardCategory'),
        ),
        migrations.AddField(
            model_name='addressordergiftcard',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Address'),
        ),
    ]
