# Generated by Django 2.1.4 on 2018-12-20 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('giftcard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcard',
            name='_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Address'),
        ),
        migrations.AddField(
            model_name='ordergiftcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcardtype',
            name='mall_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.GiftCardCategory'),
        ),
        migrations.CreateModel(
            name='AddressOrderGiftCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('giftcard.ordergiftcard',),
        ),
        migrations.CreateModel(
            name='EmailOrderGiftCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('giftcard.ordergiftcard',),
        ),
        migrations.CreateModel(
            name='SMSOrderGiftCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('giftcard.ordergiftcard',),
        ),
    ]
