# Generated by Django 2.1.4 on 2018-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_auto_20181214_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardtype',
            name='category',
            field=models.CharField(choices=[('h', 'hot'), ('m', 'mobile')], max_length=2),
        ),
    ]
