# Generated by Django 2.1.3 on 2018-11-26 08:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_auto_20181126_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOrderGiftCard',
            fields=[
                ('ordergiftcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='giftcard.OrderGiftCard')),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('giftcard.ordergiftcard',),
        ),
        migrations.CreateModel(
            name='GiftCardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='images/shop_image')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGiftCardAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SMSOrderGiftCard',
            fields=[
                ('ordergiftcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='giftcard.OrderGiftCard')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
            bases=('giftcard.ordergiftcard',),
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='gift_card',
        ),
        migrations.RenameField(
            model_name='ordergiftcard',
            old_name='order_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='giftcardtype',
            name='available_day_limit',
        ),
        migrations.RemoveField(
            model_name='giftcardtype',
            name='use_point',
        ),
        migrations.RemoveField(
            model_name='ordergiftcard',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ordergiftcard',
            name='gift_card_type',
        ),
        migrations.RemoveField(
            model_name='ordergiftcard',
            name='numbering',
        ),
        migrations.RemoveField(
            model_name='ordergiftcard',
            name='order_with',
        ),
        migrations.AddField(
            model_name='giftcardtype',
            name='category',
            field=models.CharField(choices=[('h', 'hot'), ('m', 'mobile')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergiftcard',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordergiftcard',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='GiftCard',
        ),
        migrations.AddField(
            model_name='ordergiftcardamount',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.GiftCardType'),
        ),
        migrations.AddField(
            model_name='giftcardtype',
            name='mall_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='giftcard.GiftCardCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergiftcard',
            name='gift_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='giftcard.OrderGiftCardAmount'),
            preserve_default=False,
        ),
    ]
