# Generated by Django 2.1.4 on 2018-12-18 08:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20181216_2222'),
        ('giftcard', '0002_auto_20181216_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressordergiftcard',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addressordergiftcard',
            name='ordergiftcard_ptr',
        ),
        migrations.RemoveField(
            model_name='emailordergiftcard',
            name='ordergiftcard_ptr',
        ),
        migrations.RemoveField(
            model_name='smsordergiftcard',
            name='ordergiftcard_ptr',
        ),
        migrations.AddField(
            model_name='ordergiftcard',
            name='_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Address'),
        ),
        migrations.AddField(
            model_name='ordergiftcard',
            name='_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordergiftcard',
            name='_sms',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='AddressOrderGiftCard',
        ),
        migrations.DeleteModel(
            name='EmailOrderGiftCard',
        ),
        migrations.DeleteModel(
            name='SMSOrderGiftCard',
        ),
        migrations.CreateModel(
            name='AddressOrderGiftCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('giftcard.ordergiftcard',),
        ),
        migrations.CreateModel(
            name='EmailOrderGiftCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('giftcard.ordergiftcard',),
        ),
        migrations.CreateModel(
            name='SMSOrderGiftCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('giftcard.ordergiftcard',),
        ),
    ]
