# Generated by Django 2.1.4 on 2018-12-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_remove_happygiftcard_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='happygiftcard',
            old_name='DELIVERY_TYPE',
            new_name='delivery_type',
        ),
    ]
