# Generated by Django 2.1.4 on 2018-12-14 08:45

from django.db import migrations, models
import giftcard.models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_auto_20181214_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardtype',
            name='gift_card_unique_id',
            field=models.CharField(default=giftcard.models.increment_giftcard_cnt, editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name='happygiftcard',
            name='gift_card_unique_id',
            field=models.CharField(default=giftcard.models.increment_happycard_cnt, editable=False, max_length=10),
        ),
    ]
