# Generated by Django 2.1.4 on 2018-12-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0004_auto_20181212_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='happygiftcard',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
