# Generated by Django 2.1.4 on 2018-12-15 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0005_auto_20181214_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingiftcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
