# Generated by Django 2.1.4 on 2018-12-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0005_happygiftcard_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergiftcard',
            old_name='content',
            new_name='merchant_uid',
        ),
    ]
