# Generated by Django 2.1.4 on 2018-12-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0006_pingiftcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingiftcard',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
