# Generated by Django 2.1.4 on 2018-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0006_auto_20181212_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcard',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
