# Generated by Django 2.1.4 on 2018-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0007_ordergiftcard_is_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergiftcard',
            name='full_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
