# Generated by Django 2.1.3 on 2018-11-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
    ]
