# Generated by Django 2.1.3 on 2018-11-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181128_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
