# Generated by Django 2.1.3 on 2018-11-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181128_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-pk']},
        ),
    ]
