# Generated by Django 2.1.4 on 2018-12-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0002_cash_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='hammer_or_cash',
            field=models.CharField(choices=[('hc', 'HappyCash'), ('hm', 'Hammer')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cash',
            name='use_or_save',
            field=models.CharField(choices=[('u', 'use'), ('s', 'save')], max_length=2),
        ),
    ]
