# Generated by Django 2.1.3 on 2018-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0002_cash_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
