# Generated by Django 2.1.4 on 2018-12-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0003_auto_20181214_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='content',
            new_name='merchant_uid',
        ),
    ]
